name: Build, test, and deploy container app to Azure Web App - productservicebackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_798949e6488a44cba9afef453b76393a }}
          password: ${{ secrets.AzureAppService_ContainerPassword_642361cd774b4d45983d1ae58d0b84b1 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: index.docker.io/pramudithsj/productcatlogservice:main
          file: ./Dockerfile

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=pramudithasj
            -Dsonar.projectKey=pramudithaSJ_productcatlogservice
  deploy:
    runs-on: ubuntu-latest
    needs: [build, sonarcloud]
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "productservicebackend"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e17777c016624cab9906ca21a5ade2c7 }}
          images: "index.docker.io/pramudithsj/productcatlogservice:main"
